### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by MARTIMM** [MARTIMM/BSON#12]
Thinking about undefined, it is deprecated in BSON. I can code this in some way or another or leave the key-value out all together. When back in perl it will just show the value as (Any) (a typed undefined value) no matter if the key was in the document or not. So in the last case it will save space and time leaving the pair out.

**Comment by xdg** [comment]
In Perl 5 land, a Perl 5 undef works the way other languages use null/nil, which is why we map it to BSON null.  If we ever see BSON undef decoding, we treat it like BSON null and turn it into a Perl 5 undef.  The reason you might not want to leave it out is that "exists" is a valid MongoDB concept as well as a Perl one, distinct from "is null".

**Comment by MARTIMM** [comment]
Hi David,
Thanks for your comment. I've found a kind of solution to encode any undefined value to the BSON NULL and to decode it in a untyped Any object.
Cheers,
Marcel
